/* eslint-disable no-console */
/**
 * Deterministic seed generator for the sandbox measurements fixture.
 *
 * Run from repo root:
 *   npx ts-node src/measurement/sandbox/seed.ts
 *
 * Edit COUNTRIES / REFERENCE_DATE / per-country counts below to extend
 * coverage, then re-run and commit the regenerated JSON. The output is
 * deterministic — same inputs produce the same JSON, so vendor integrations
 * see stable data across runs.
 */
import * as fs from 'fs';
import * as path from 'path';
import type { MeasurementSandboxDto, EntityType } from './sandbox.dto';

interface CountrySpec {
  iso3: string;
  iso2: string;
  health_count: number;
  school_count: number;
}

// Add a country here, set counts, re-run.
const COUNTRIES: CountrySpec[] = [
  { iso3: 'KEN', iso2: 'KE', health_count: 12, school_count: 8 },
  { iso3: 'BRA', iso2: 'BR', health_count: 10, school_count: 10 },
  { iso3: 'UZB', iso2: 'UZ', health_count: 8, school_count: 7 },
  { iso3: 'RWA', iso2: 'RW', health_count: 10, school_count: 5 },
  { iso3: 'GHA', iso2: 'GH', health_count: 8, school_count: 7 },
  { iso3: 'IND', iso2: 'IN', health_count: 10, school_count: 5 },
];

// "Today" anchor for the fixture date range. Frozen so output is stable.
const REFERENCE_DATE = new Date('2026-04-29T00:00:00Z');
const DATE_SPREAD_DAYS = 90;

// Exposed so the service can map ?country_iso3_code=KEN -> stored "KE".
const ISO3_TO_ISO2: Record<string, string> = {};
for (const c of COUNTRIES) ISO3_TO_ISO2[c.iso3] = c.iso2;

function generate(): MeasurementSandboxDto[] {
  const rows: MeasurementSandboxDto[] = [];
  let regId = 1000;
  let healthCounter = 0;
  let schoolCounter = 0;

  const pushRow = (country: CountrySpec, entity_type: EntityType, i: number) => {
    regId++;
    const idx = rows.length;
    // Spread across the date range with deterministic jitter so rows aren't
    // colocated on a single day per country.
    const daysAgo = (idx * 8.3 + i * 1.7) % DATE_SPREAD_DAYS;
    const ts = new Date(
      REFERENCE_DATE.getTime() -
        Math.floor(daysAgo * 86_400_000) -
        i * 3_617_000,
    );
    const created = new Date(ts.getTime() + 60_000);

    const base = {
      timestamp: ts,
      browserId: `fixture-browser-${regId}`,
      download: Number((8 + ((idx * 3) % 50) + 0.4).toFixed(2)),
      upload: Number((2 + ((idx * 2) % 20) + 0.3).toFixed(2)),
      latency: 30 + ((idx * 7) % 100),
      registration_id: String(regId),
      country_code: country.iso2,
      ip_address: `10.${(idx % 250) + 1}.0.${(i % 250) + 1}`,
      app_version: '1.2.3',
      source: 'DailyCheckApp',
      created_at: created,
      device_hardware_id: `hw-fixture-${regId}`,
    };

    if (entity_type === 'health') {
      healthCounter++;
      rows.push({
        ...base,
        entity_type: 'health',
        school_id: null,
        giga_id_school: null,
        giga_id_health: `h-${country.iso2.toLowerCase()}-${String(healthCounter).padStart(4, '0')}`,
      });
    } else {
      schoolCounter++;
      rows.push({
        ...base,
        entity_type: 'school',
        school_id: `${country.iso2}-school-${schoolCounter}`,
        giga_id_school: `s-${country.iso2.toLowerCase()}-${String(schoolCounter).padStart(4, '0')}`,
        giga_id_health: null,
      });
    }
  };

  for (const country of COUNTRIES) {
    for (let i = 0; i < country.health_count; i++) pushRow(country, 'health', i);
    for (let i = 0; i < country.school_count; i++) pushRow(country, 'school', i);
  }

  return rows;
}

function main() {
  const rows = generate();
  const out = {
    _generated: new Date().toISOString(),
    _note:
      'Auto-generated by src/measurement/sandbox/seed.ts. Do not edit by hand — re-run the seed to regenerate.',
    iso3_to_iso2: ISO3_TO_ISO2,
    measurements: rows,
  };

  const target = path.join(__dirname, 'fixtures.measurements.json');
  fs.writeFileSync(target, JSON.stringify(out, null, 2) + '\n', 'utf-8');
  console.log(
    `Wrote ${rows.length} fixture rows for ${COUNTRIES.length} countries to ${target}`,
  );
}

main();
