
export const schoolMasterSelect = {
    id: true,
    created: true,
    modified: true,
    name: true,
    timezone: true,
    gps_confidence: true,
    altitude: true,
    address: true,
    postal_code: true,
    email: true,
    education_level: true,
    environment: true,
    school_type: true,
    country_id: true,
    location_id: true,
    admin_2_name: true,
    admin_3_name: true,
    admin_4_name: true,
    external_id: true,
    admin_1_name: true,
    last_weekly_status_id: true,
    name_lower: true,
    giga_id_school: true,
    education_level_regional: true,
    feature_flags: true,
    created_at: true,
    country_code: true,
    deleted: true,
    last_school_static_id: true,
  };