-- CreateTable
CREATE TABLE "master_sync_school_static" (
    "id" SERIAL NOT NULL,
    "created" TIMESTAMPTZ NOT NULL,
    "modified" TIMESTAMPTZ NOT NULL,
    "latitude" DOUBLE PRECISION,
    "longitude" DOUBLE PRECISION,
    "admin1_id_giga" VARCHAR(50),
    "admin2_id_giga" VARCHAR(50),
    "school_establishment_year" INTEGER,
    "download_speed_contracted" DOUBLE PRECISION,
    "num_computers_desired" INTEGER,
    "electricity_type" VARCHAR(255),
    "num_adm_personnel" INTEGER,
    "num_students" INTEGER,
    "num_teachers" INTEGER,
    "num_classrooms" INTEGER,
    "num_latrines" INTEGER,
    "water_availability" BOOLEAN,
    "electricity_availability" BOOLEAN,
    "computer_lab" BOOLEAN,
    "num_computers" INTEGER,
    "connectivity_govt" BOOLEAN,
    "connectivity_type_govt" VARCHAR(255),
    "connectivity_type" VARCHAR(255),
    "connectivity_type_root" VARCHAR(255),
    "cellular_coverage_availability" BOOLEAN,
    "cellular_coverage_type" VARCHAR(255),
    "fiber_node_distance" DOUBLE PRECISION,
    "microwave_node_distance" DOUBLE PRECISION,
    "schools_within_1km" INTEGER,
    "schools_within_2km" INTEGER,
    "schools_within_3km" INTEGER,
    "nearest_lte_distance" DOUBLE PRECISION,
    "nearest_umts_distance" DOUBLE PRECISION,
    "nearest_gsm_distance" DOUBLE PRECISION,
    "nearest_nr_distance" DOUBLE PRECISION,
    "pop_within_1km" INTEGER,
    "pop_within_2km" INTEGER,
    "pop_within_3km" INTEGER,
    "school_data_source" VARCHAR(255),
    "school_data_collection_year" INTEGER,
    "school_data_collection_modality" VARCHAR(255),
    "school_location_ingestion_timestamp" TIMESTAMP(3),
    "connectivity_govt_ingestion_timestamp" TIMESTAMP(3),
    "connectivity_govt_collection_year" INTEGER,
    "disputed_region" BOOLEAN NOT NULL,
    "connectivity_rt" BOOLEAN,
    "connectivity_rt_datasource" VARCHAR(255),
    "connectivity_rt_ingestion_timestamp" TIMESTAMP(3),
    "connectivity" BOOLEAN,
    "download_speed_benchmark" DOUBLE PRECISION,
    "computer_availability" BOOLEAN,
    "num_students_girls" INTEGER,
    "num_students_boys" INTEGER,
    "num_students_other" INTEGER,
    "num_teachers_female" INTEGER,
    "num_teachers_male" INTEGER,
    "teachers_trained" BOOLEAN,
    "sustainable_business_model" BOOLEAN,
    "device_availability" BOOLEAN,
    "num_tablets" INTEGER,
    "num_robotic_equipment" INTEGER,
    "building_id_govt" VARCHAR(255),
    "num_schools_per_building" INTEGER,
    "version" INTEGER,
    "school_id" BIGINT,

    CONSTRAINT "master_sync_school_static_pkey" PRIMARY KEY ("id"),
    CONSTRAINT master_sync_school_static_connectivity_govt_collection_ye_check CHECK (connectivity_govt_collection_year >= 0),
    CONSTRAINT master_sync_school_static_num_adm_personnel_check CHECK (num_adm_personnel >= 0),
    CONSTRAINT master_sync_school_static_num_classrooms_check CHECK (num_classrooms >= 0),
    CONSTRAINT master_sync_school_static_num_computers_check CHECK (num_computers >= 0),
    CONSTRAINT master_sync_school_static_num_computers_desired_check CHECK (num_computers_desired >= 0),
    CONSTRAINT master_sync_school_static_num_latrines_check CHECK (num_latrines >= 0),
    CONSTRAINT master_sync_school_static_num_robotic_equipment_check CHECK (num_robotic_equipment >= 0),
    CONSTRAINT master_sync_school_static_num_schools_per_building_check CHECK (num_schools_per_building >= 0),
    CONSTRAINT master_sync_school_static_num_students_boys_check CHECK (num_students_boys >= 0),
    CONSTRAINT master_sync_school_static_num_students_check CHECK (num_students >= 0),
    CONSTRAINT master_sync_school_static_num_students_girls_check CHECK (num_students_girls >= 0),
    CONSTRAINT master_sync_school_static_num_students_other_check CHECK (num_students_other >= 0),
    CONSTRAINT master_sync_school_static_num_tablets_check CHECK (num_tablets >= 0),
    CONSTRAINT master_sync_school_static_num_teachers_check CHECK (num_teachers >= 0),
    CONSTRAINT master_sync_school_static_num_teachers_female_check CHECK (num_teachers_female >= 0),
    CONSTRAINT master_sync_school_static_num_teachers_male_check CHECK (num_teachers_male >= 0),
    CONSTRAINT master_sync_school_static_pop_within_1km_check CHECK (pop_within_1km >= 0),
    CONSTRAINT master_sync_school_static_pop_within_2km_check CHECK (pop_within_2km >= 0),
    CONSTRAINT master_sync_school_static_pop_within_3km_check CHECK (pop_within_3km >= 0),
    CONSTRAINT master_sync_school_static_school_data_collection_year_check CHECK (school_data_collection_year >= 0),
    CONSTRAINT master_sync_school_static_school_establishment_year_check CHECK (school_establishment_year >= 0),
    CONSTRAINT master_sync_school_static_schools_within_1km_check CHECK (schools_within_1km >= 0),
    CONSTRAINT master_sync_school_static_schools_within_2km_check CHECK (schools_within_2km >= 0),
    CONSTRAINT master_sync_school_static_schools_within_3km_check CHECK (schools_within_3km >= 0),
    CONSTRAINT master_sync_school_static_version_check CHECK (version >= 0)
);

-- CreateIndex
CREATE INDEX "master_sync_school_static_school_id_00765da3" ON "master_sync_school_static"("school_id");

-- AddForeignKey
ALTER TABLE "master_sync_school_static" ADD CONSTRAINT "master_sync_school_static_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "school"("id") ON DELETE SET NULL ON UPDATE CASCADE;
