-- AlterTable
ALTER TABLE "master_sync_school_static"
    ADD COLUMN "created" TIMESTAMPTZ NOT NULL,
    ADD COLUMN "modified" TIMESTAMPTZ NOT NULL,
    ADD COLUMN "latitude" DOUBLE PRECISION,
    ADD COLUMN "longitude" DOUBLE PRECISION,
    ADD COLUMN "admin1_id_giga" VARCHAR(50),
    ADD COLUMN "admin2_id_giga" VARCHAR(50),
    ADD COLUMN "school_establishment_year" INTEGER,
    ADD COLUMN "download_speed_contracted" DOUBLE PRECISION,
    ADD COLUMN "num_computers_desired" INTEGER,
    ADD COLUMN "electricity_type" VARCHAR(255),
    ADD COLUMN "num_adm_personnel" INTEGER,
    ADD COLUMN "num_students" INTEGER,
    ADD COLUMN "num_teachers" INTEGER,
    ADD COLUMN "num_classrooms" INTEGER,
    ADD COLUMN "num_latrines" INTEGER,
    ADD COLUMN "water_availability" BOOLEAN,
    ADD COLUMN "electricity_availability" BOOLEAN,
    ADD COLUMN "computer_lab" BOOLEAN,
    ADD COLUMN "num_computers" INTEGER,
    ADD COLUMN "connectivity_govt" BOOLEAN,
    ADD COLUMN "connectivity_type_govt" VARCHAR(255),
    ADD COLUMN "connectivity_type" VARCHAR(255),
    ADD COLUMN "connectivity_type_root" VARCHAR(255),
    ADD COLUMN "cellular_coverage_availability" BOOLEAN,
    ADD COLUMN "cellular_coverage_type" VARCHAR(255),
    ADD COLUMN "fiber_node_distance" DOUBLE PRECISION,
    ADD COLUMN "microwave_node_distance" DOUBLE PRECISION,
    ADD COLUMN "schools_within_1km" INTEGER,
    ADD COLUMN "schools_within_2km" INTEGER,
    ADD COLUMN "schools_within_3km" INTEGER,
    ADD COLUMN "nearest_lte_distance" DOUBLE PRECISION,
    ADD COLUMN "nearest_umts_distance" DOUBLE PRECISION,
    ADD COLUMN "nearest_gsm_distance" DOUBLE PRECISION,
    ADD COLUMN "nearest_nr_distance" DOUBLE PRECISION,
    ADD COLUMN "pop_within_1km" INTEGER,
    ADD COLUMN "pop_within_2km" INTEGER,
    ADD COLUMN "pop_within_3km" INTEGER,
    ADD COLUMN "school_data_source" VARCHAR(255),
    ADD COLUMN "school_data_collection_year" INTEGER,
    ADD COLUMN "school_data_collection_modality" VARCHAR(255),
    ADD COLUMN "school_location_ingestion_timestamp" TIMESTAMP(3),
    ADD COLUMN "connectivity_govt_ingestion_timestamp" TIMESTAMP(3),
    ADD COLUMN "connectivity_govt_collection_year" INTEGER,
    ADD COLUMN "disputed_region" BOOLEAN NOT NULL,
    ADD COLUMN "connectivity_rt" BOOLEAN,
    ADD COLUMN "connectivity_rt_datasource" VARCHAR(255),
    ADD COLUMN "connectivity_rt_ingestion_timestamp" TIMESTAMP(3),
    ADD COLUMN "connectivity" BOOLEAN,
    ADD COLUMN "download_speed_benchmark" DOUBLE PRECISION,
    ADD COLUMN "computer_availability" BOOLEAN,
    ADD COLUMN "num_students_girls" INTEGER,
    ADD COLUMN "num_students_boys" INTEGER,
    ADD COLUMN "num_students_other" INTEGER,
    ADD COLUMN "num_teachers_female" INTEGER,
    ADD COLUMN "num_teachers_male" INTEGER,
    ADD COLUMN "teachers_trained" BOOLEAN,
    ADD COLUMN "sustainable_business_model" BOOLEAN,
    ADD COLUMN "device_availability" BOOLEAN,
    ADD COLUMN "num_tablets" INTEGER,
    ADD COLUMN "num_robotic_equipment" INTEGER,
    ADD COLUMN "building_id_govt" VARCHAR(255),
    ADD COLUMN "num_schools_per_building" INTEGER,
    ADD COLUMN "version" INTEGER,
    ADD COLUMN "school_id" BIGINT,
    ADD CONSTRAINT master_sync_school_static_connectivity_govt_collection_ye_check CHECK (connectivity_govt_collection_year >= 0),
    ADD CONSTRAINT master_sync_school_static_num_adm_personnel_check CHECK (num_adm_personnel >= 0),
    ADD CONSTRAINT master_sync_school_static_num_classrooms_check CHECK (num_classrooms >= 0),
    ADD CONSTRAINT master_sync_school_static_num_computers_check CHECK (num_computers >= 0),
    ADD CONSTRAINT master_sync_school_static_num_computers_desired_check CHECK (num_computers_desired >= 0),
    ADD CONSTRAINT master_sync_school_static_num_latrines_check CHECK (num_latrines >= 0),
    ADD CONSTRAINT master_sync_school_static_num_robotic_equipment_check CHECK (num_robotic_equipment >= 0),
    ADD CONSTRAINT master_sync_school_static_num_schools_per_building_check CHECK (num_schools_per_building >= 0),
    ADD CONSTRAINT master_sync_school_static_num_students_boys_check CHECK (num_students_boys >= 0),
    ADD CONSTRAINT master_sync_school_static_num_students_check CHECK (num_students >= 0),
    ADD CONSTRAINT master_sync_school_static_num_students_girls_check CHECK (num_students_girls >= 0),
    ADD CONSTRAINT master_sync_school_static_num_students_other_check CHECK (num_students_other >= 0),
    ADD CONSTRAINT master_sync_school_static_num_tablets_check CHECK (num_tablets >= 0),
    ADD CONSTRAINT master_sync_school_static_num_teachers_check CHECK (num_teachers >= 0),
    ADD CONSTRAINT master_sync_school_static_num_teachers_female_check CHECK (num_teachers_female >= 0),
    ADD CONSTRAINT master_sync_school_static_num_teachers_male_check CHECK (num_teachers_male >= 0),
    ADD CONSTRAINT master_sync_school_static_pop_within_1km_check CHECK (pop_within_1km >= 0),
    ADD CONSTRAINT master_sync_school_static_pop_within_2km_check CHECK (pop_within_2km >= 0),
    ADD CONSTRAINT master_sync_school_static_pop_within_3km_check CHECK (pop_within_3km >= 0),
    ADD CONSTRAINT master_sync_school_static_school_data_collection_year_check CHECK (school_data_collection_year >= 0),
    ADD CONSTRAINT master_sync_school_static_school_establishment_year_check CHECK (school_establishment_year >= 0),
    ADD CONSTRAINT master_sync_school_static_schools_within_1km_check CHECK (schools_within_1km >= 0),
    ADD CONSTRAINT master_sync_school_static_schools_within_2km_check CHECK (schools_within_2km >= 0),
    ADD CONSTRAINT master_sync_school_static_schools_within_3km_check CHECK (schools_within_3km >= 0),
    ADD CONSTRAINT master_sync_school_static_version_check CHECK (version >= 0);

-- CreateIndex
CREATE INDEX "master_sync_school_static_school_id_00765da3" ON "master_sync_school_static"("school_id");

-- AddForeignKey
ALTER TABLE "master_sync_school_static" ADD CONSTRAINT "master_sync_school_static_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "school"("id") ON DELETE SET NULL ON UPDATE CASCADE;
