	INSERT INTO public.country(id, name, code) VALUES (24, 'Afghanistan', 'AF');
	INSERT INTO public.country(id, name, code) VALUES (223, 'Åland Islands', 'AX');
	INSERT INTO public.country(id, name, code) VALUES (178, 'Albania', 'AL');
	INSERT INTO public.country(id, name, code) VALUES (198, 'Algeria', 'DZ');
	INSERT INTO public.country(id, name, code) VALUES (236, 'Andorra', 'AD');
	INSERT INTO public.country(id, name, code) VALUES (89, 'Angola', 'AO');
	INSERT INTO public.country(id, name, code) VALUES (222, 'Anguilla', 'AI');
	INSERT INTO public.country(id, name, code) VALUES (226, 'Antarctica', 'AQ');
	INSERT INTO public.country(id, name, code) VALUES (238, 'Antigua and Barbuda', 'AG');
	INSERT INTO public.country(id, name, code) VALUES (143, 'Argentina', 'AR');
	INSERT INTO public.country(id, name, code) VALUES (187, 'Armenia', 'AM');
	INSERT INTO public.country(id, name, code) VALUES (220, 'Aruba', 'AW');
	INSERT INTO public.country(id, name, code) VALUES (239, 'Australia', 'AU');
	INSERT INTO public.country(id, name, code) VALUES (240, 'Austria', 'AT');
	INSERT INTO public.country(id, name, code) VALUES (188, 'Azerbaijan', 'AZ');
	INSERT INTO public.country(id, name, code) VALUES (228, 'Bahamas', 'BS');
	INSERT INTO public.country(id, name, code) VALUES (243, 'Bahrain', 'BH');
	INSERT INTO public.country(id, name, code) VALUES (53, 'Bangladesh', 'BD');
	INSERT INTO public.country(id, name, code) VALUES (134, 'Barbados', 'BB');
	INSERT INTO public.country(id, name, code) VALUES (172, 'Belarus', 'BY');
	INSERT INTO public.country(id, name, code) VALUES (241, 'Belgium', 'BE');
	INSERT INTO public.country(id, name, code) VALUES (191, 'Belize', 'BZ');
	INSERT INTO public.country(id, name, code) VALUES (152, 'Benin', 'BJ');
	INSERT INTO public.country(id, name, code) VALUES (237, 'Bermuda', 'BM');
	INSERT INTO public.country(id, name, code) VALUES (176, 'Bhutan', 'BT');
	INSERT INTO public.country(id, name, code) VALUES (40, 'Bolivia (Plurinational State of)', 'BO');
	INSERT INTO public.country(id, name, code) VALUES (242, 'Bonaire', 'BQ');
	INSERT INTO public.country(id, name, code) VALUES (200, 'Bosnia and Herzegovina', 'BA');
	INSERT INTO public.country(id, name, code) VALUES (201, 'Botswana', 'BW');
	INSERT INTO public.country(id, name, code) VALUES (245, 'Bouvet Island', 'BV');
	INSERT INTO public.country(id, name, code) VALUES (144, 'Brazil', 'BR');
	INSERT INTO public.country(id, name, code) VALUES (332, 'British Virgin Islands', 'VG');
	INSERT INTO public.country(id, name, code) VALUES (221, 'Brunei Darussalam', 'BN');
	INSERT INTO public.country(id, name, code) VALUES (167, 'Bulgaria', 'BG');
	INSERT INTO public.country(id, name, code) VALUES (46, 'Burkina Faso', 'BF');
	INSERT INTO public.country(id, name, code) VALUES (141, 'Burundi', 'BI');
	INSERT INTO public.country(id, name, code) VALUES (159, 'Cabo Verde', 'CV');
	INSERT INTO public.country(id, name, code) VALUES (26, 'Cambodia', 'KH');
	INSERT INTO public.country(id, name, code) VALUES (127, 'Cameroon', 'CM');
	INSERT INTO public.country(id, name, code) VALUES (229, 'Canada', 'CA');
	INSERT INTO public.country(id, name, code) VALUES (248, 'Cayman Islands', 'KY');
	INSERT INTO public.country(id, name, code) VALUES (148, 'Central African Republic', 'CF');
	INSERT INTO public.country(id, name, code) VALUES (131, 'Chad', 'TD');
	INSERT INTO public.country(id, name, code) VALUES (294, 'Chagos Archipelagio', 'IO');
	INSERT INTO public.country(id, name, code) VALUES (182, 'Chile', 'CL');
	INSERT INTO public.country(id, name, code) VALUES (3, 'China', 'CN');
	INSERT INTO public.country(id, name, code) VALUES (232, 'Christmas Island', 'CX');
	INSERT INTO public.country(id, name, code) VALUES (246, 'Cocos (Keeling) Islands', 'CC');
	INSERT INTO public.country(id, name, code) VALUES (147, 'Colombia', 'CO');
	INSERT INTO public.country(id, name, code) VALUES (202, 'Comoros', 'KM');
	INSERT INTO public.country(id, name, code) VALUES (157, 'Congo', 'CG');
	INSERT INTO public.country(id, name, code) VALUES (231, 'Cook Islands', 'CK');
	INSERT INTO public.country(id, name, code) VALUES (192, 'Costa Rica', 'CR');
	INSERT INTO public.country(id, name, code) VALUES (50, 'Côte d''Ivoire', 'CI');
	INSERT INTO public.country(id, name, code) VALUES (183, 'Croatia', 'HR');
	INSERT INTO public.country(id, name, code) VALUES (203, 'Cuba', 'CU');
	INSERT INTO public.country(id, name, code) VALUES (247, 'Curaçao', 'CW');
	INSERT INTO public.country(id, name, code) VALUES (233, 'Cyprus', 'CY');
	INSERT INTO public.country(id, name, code) VALUES (213, 'Czechia', 'CZ');
	INSERT INTO public.country(id, name, code) VALUES (135, 'Democratic People''s Republic of Korea', 'KP');
	INSERT INTO public.country(id, name, code) VALUES (28, 'Democratic Republic of the Congo', 'CD');
	INSERT INTO public.country(id, name, code) VALUES (234, 'Denmark', 'DK');
	INSERT INTO public.country(id, name, code) VALUES (129, 'Djibouti', 'DJ');
	INSERT INTO public.country(id, name, code) VALUES (249, 'Dominica', 'DM');
	INSERT INTO public.country(id, name, code) VALUES (185, 'Dominican Republic', 'DO');
	INSERT INTO public.country(id, name, code) VALUES (145, 'Ecuador', 'EC');
	INSERT INTO public.country(id, name, code) VALUES (156, 'Egypt', 'EG');
	INSERT INTO public.country(id, name, code) VALUES (184, 'El Salvador', 'SV');
	INSERT INTO public.country(id, name, code) VALUES (158, 'Equatorial Guinea', 'GQ');
	INSERT INTO public.country(id, name, code) VALUES (142, 'Eritrea', 'ER');
	INSERT INTO public.country(id, name, code) VALUES (217, 'Estonia', 'EE');
	INSERT INTO public.country(id, name, code) VALUES (165, 'Eswatini', 'SZ');
	INSERT INTO public.country(id, name, code) VALUES (35, 'Ethiopia', 'ET');
	INSERT INTO public.country(id, name, code) VALUES (251, 'Falkland Islands (Malvinas)', 'FK');
	INSERT INTO public.country(id, name, code) VALUES (253, 'Faroe Islands', 'FO');
	INSERT INTO public.country(id, name, code) VALUES (250, 'Fiji', 'FJ');
	INSERT INTO public.country(id, name, code) VALUES (218, 'Finland', 'FI');
	INSERT INTO public.country(id, name, code) VALUES (252, 'France', 'FR');
	INSERT INTO public.country(id, name, code) VALUES (259, 'French Guiana', 'GF');
	INSERT INTO public.country(id, name, code) VALUES (289, 'French Polynesia', 'PF');
	INSERT INTO public.country(id, name, code) VALUES (227, 'French Southern Territories', 'TF');
	INSERT INTO public.country(id, name, code) VALUES (160, 'Gabon', 'GA');
	INSERT INTO public.country(id, name, code) VALUES (162, 'Gambia', 'GM');
	INSERT INTO public.country(id, name, code) VALUES (205, 'Georgia', 'GE');
	INSERT INTO public.country(id, name, code) VALUES (214, 'Germany', 'DE');
	INSERT INTO public.country(id, name, code) VALUES (149, 'Ghana', 'GH');
	INSERT INTO public.country(id, name, code) VALUES (257, 'Gibraltar', 'GI');
	INSERT INTO public.country(id, name, code) VALUES (190, 'Greece', 'GR');
	INSERT INTO public.country(id, name, code) VALUES (235, 'Greenland', 'GL');
	INSERT INTO public.country(id, name, code) VALUES (258, 'Grenada', 'GD');
	INSERT INTO public.country(id, name, code) VALUES (261, 'Guadeloupe', 'GP');
	INSERT INTO public.country(id, name, code) VALUES (260, 'Guam', 'GU');
	INSERT INTO public.country(id, name, code) VALUES (193, 'Guatemala', 'GT');
	INSERT INTO public.country(id, name, code) VALUES (256, 'Guernsey', 'GG');
	INSERT INTO public.country(id, name, code) VALUES (54, 'Guinea', 'GN');
	INSERT INTO public.country(id, name, code) VALUES (151, 'Guinea-Bissau', 'GW');
	INSERT INTO public.country(id, name, code) VALUES (206, 'Guyana', 'GY');
	INSERT INTO public.country(id, name, code) VALUES (43, 'Haiti', 'HT');
	INSERT INTO public.country(id, name, code) VALUES (262, 'Heard Island and McDonald Islands', 'HM');
	INSERT INTO public.country(id, name, code) VALUES (318, 'Holy See', 'VA');
	INSERT INTO public.country(id, name, code) VALUES (196, 'Honduras', 'HN');
	INSERT INTO public.country(id, name, code) VALUES (219, 'Hong Kong', 'HK');
	INSERT INTO public.country(id, name, code) VALUES (291, 'Hungary', 'HU');
	INSERT INTO public.country(id, name, code) VALUES (295, 'Iceland', 'IS');
	INSERT INTO public.country(id, name, code) VALUES (45, 'India', 'IN');
	INSERT INTO public.country(id, name, code) VALUES (27, 'Indonesia', 'ID');
	INSERT INTO public.country(id, name, code) VALUES (155, 'Iran (Islamic Republic of)', 'IR');
	INSERT INTO public.country(id, name, code) VALUES (13, 'Iraq', 'IQ');
	INSERT INTO public.country(id, name, code) VALUES (267, 'Ireland', 'IE');
	INSERT INTO public.country(id, name, code) VALUES (292, 'Isle of Man', 'IM');
	INSERT INTO public.country(id, name, code) VALUES (296, 'Israel', 'IL');
	INSERT INTO public.country(id, name, code) VALUES (297, 'Italy', 'IT');
	INSERT INTO public.country(id, name, code) VALUES (132, 'Jamaica', 'JM');
	INSERT INTO public.country(id, name, code) VALUES (268, 'Japan', 'JP');
	INSERT INTO public.country(id, name, code) VALUES (298, 'Jersey', 'JE');
	INSERT INTO public.country(id, name, code) VALUES (18, 'Jordan', 'JO');
	INSERT INTO public.country(id, name, code) VALUES (29, 'Kazakhstan', 'KZ');
	INSERT INTO public.country(id, name, code) VALUES (5, 'Kenya', 'KE');
	INSERT INTO public.country(id, name, code) VALUES (269, 'Kiribati', 'KI');
	INSERT INTO public.country(id, name, code) VALUES (163, 'Kosovo', 'XK');
	INSERT INTO public.country(id, name, code) VALUES (271, 'Kuwait', 'KW');
	INSERT INTO public.country(id, name, code) VALUES (39, 'Kyrgyzstan', 'KG');
	INSERT INTO public.country(id, name, code) VALUES (123, 'Lao People''s Democratic Republic', 'LA');
	INSERT INTO public.country(id, name, code) VALUES (263, 'Latvia', 'LV');
	INSERT INTO public.country(id, name, code) VALUES (9, 'Lebanon', 'LB');
	INSERT INTO public.country(id, name, code) VALUES (173, 'Lesotho', 'LS');
	INSERT INTO public.country(id, name, code) VALUES (37, 'Liberia', 'LR');
	INSERT INTO public.country(id, name, code) VALUES (48, 'Libya', 'LY');
	INSERT INTO public.country(id, name, code) VALUES (300, 'Liechtenstein', 'LI');
	INSERT INTO public.country(id, name, code) VALUES (272, 'Lithuania', 'LT');
	INSERT INTO public.country(id, name, code) VALUES (273, 'Luxembourg', 'LX');
	INSERT INTO public.country(id, name, code) VALUES (301, 'Macao', 'MO');
	INSERT INTO public.country(id, name, code) VALUES (87, 'Madagascar', 'MG');
	INSERT INTO public.country(id, name, code) VALUES (44, 'Malawi', 'MW');
	INSERT INTO public.country(id, name, code) VALUES (154, 'Malaysia', 'MY');
	INSERT INTO public.country(id, name, code) VALUES (177, 'Maldives', 'MV');
	INSERT INTO public.country(id, name, code) VALUES (125, 'Mali', 'ML');
	INSERT INTO public.country(id, name, code) VALUES (302, 'Malta', 'MT');
	INSERT INTO public.country(id, name, code) VALUES (275, 'Marshall Islands', 'MH');
	INSERT INTO public.country(id, name, code) VALUES (306, 'Martinique', 'MQ');
	INSERT INTO public.country(id, name, code) VALUES (153, 'Mauritania', 'MR');
	INSERT INTO public.country(id, name, code) VALUES (277, 'Mauritius', 'MU');
	INSERT INTO public.country(id, name, code) VALUES (307, 'Mayotte', 'YT');
	INSERT INTO public.country(id, name, code) VALUES (146, 'Mexico', 'MX');
	INSERT INTO public.country(id, name, code) VALUES (254, 'Micronesia (Federated States of)', 'FM');
	INSERT INTO public.country(id, name, code) VALUES (316, 'Midway Islands', 'MI');
	INSERT INTO public.country(id, name, code) VALUES (274, 'Monaco', 'MC');
	INSERT INTO public.country(id, name, code) VALUES (175, 'Mongolia', 'MN');
	INSERT INTO public.country(id, name, code) VALUES (180, 'Montenegro', 'ME');
	INSERT INTO public.country(id, name, code) VALUES (276, 'Montserrat', 'MS');
	INSERT INTO public.country(id, name, code) VALUES (197, 'Morocco', 'MA');
	INSERT INTO public.country(id, name, code) VALUES (52, 'Mozambique', 'MZ');
	INSERT INTO public.country(id, name, code) VALUES (8, 'Myanmar', 'MM');
	INSERT INTO public.country(id, name, code) VALUES (164, 'Namibia', 'NA');
	INSERT INTO public.country(id, name, code) VALUES (278, 'Nauru', 'NR');
	INSERT INTO public.country(id, name, code) VALUES (6, 'Nepal', 'NP');
	INSERT INTO public.country(id, name, code) VALUES (311, 'Netherlands', 'NL');
	INSERT INTO public.country(id, name, code) VALUES (308, 'New Caledonia', 'NC');
	INSERT INTO public.country(id, name, code) VALUES (279, 'New Zealand', 'NZ');
	INSERT INTO public.country(id, name, code) VALUES (207, 'Nicaragua', 'NI');
	INSERT INTO public.country(id, name, code) VALUES (126, 'Niger', 'NE');
	INSERT INTO public.country(id, name, code) VALUES (23, 'Nigeria', 'NG');
	INSERT INTO public.country(id, name, code) VALUES (310, 'Niue', 'NU');
	INSERT INTO public.country(id, name, code) VALUES (309, 'Norfolk Island', 'NF');
	INSERT INTO public.country(id, name, code) VALUES (305, 'Northern Mariana Islands', 'MP');
	INSERT INTO public.country(id, name, code) VALUES (266, 'Norway', 'NO');
	INSERT INTO public.country(id, name, code) VALUES (280, 'Oman', 'OM');
	INSERT INTO public.country(id, name, code) VALUES (25, 'Pakistan', 'PK');
	INSERT INTO public.country(id, name, code) VALUES (287, 'Palau', 'PW');
	INSERT INTO public.country(id, name, code) VALUES (21, 'Palestine, State of', 'PS');
	INSERT INTO public.country(id, name, code) VALUES (194, 'Panama', 'PA');
	INSERT INTO public.country(id, name, code) VALUES (136, 'Papua New Guinea', 'PG');
	INSERT INTO public.country(id, name, code) VALUES (195, 'Paraguay', 'PY');
	INSERT INTO public.country(id, name, code) VALUES (186, 'Peru', 'PE');
	INSERT INTO public.country(id, name, code) VALUES (20, 'Philippines', 'PH');
	INSERT INTO public.country(id, name, code) VALUES (286, 'Pitcairn', 'PN');
	INSERT INTO public.country(id, name, code) VALUES (264, 'Poland', 'PL');
	INSERT INTO public.country(id, name, code) VALUES (288, 'Portugal', 'PT');
	INSERT INTO public.country(id, name, code) VALUES (265, 'Puerto Rico', 'PR');
	INSERT INTO public.country(id, name, code) VALUES (290, 'Qatar', 'QA');
	INSERT INTO public.country(id, name, code) VALUES (270, 'Republic of Korea', 'KP1');
	INSERT INTO public.country(id, name, code) VALUES (170, 'Republic of Moldova', 'MD');
	INSERT INTO public.country(id, name, code) VALUES (303, 'Réunion', 'RE');
	INSERT INTO public.country(id, name, code) VALUES (171, 'Romania', 'RO');
	INSERT INTO public.country(id, name, code) VALUES (304, 'Russian Federation', 'RU');
	INSERT INTO public.country(id, name, code) VALUES (32, 'Rwanda', 'RW');
	INSERT INTO public.country(id, name, code) VALUES (244, 'Saint Barthélemy', 'BL');
	INSERT INTO public.country(id, name, code) VALUES (282, 'Saint Helena', 'SH');
	INSERT INTO public.country(id, name, code) VALUES (299, 'Saint Kitts and Nevis', 'KN');
	INSERT INTO public.country(id, name, code) VALUES (285, 'Saint Lucia', 'LC');
	INSERT INTO public.country(id, name, code) VALUES (293, 'Saint Martin', 'MF');
	INSERT INTO public.country(id, name, code) VALUES (327, 'Saint Pierre et Miquelon', 'PM');
	INSERT INTO public.country(id, name, code) VALUES (331, 'Saint Vincent and the Grenadines', 'VC');
	INSERT INTO public.country(id, name, code) VALUES (335, 'Samoa', 'WS');
	INSERT INTO public.country(id, name, code) VALUES (328, 'San Marino', 'SM');
	INSERT INTO public.country(id, name, code) VALUES (161, 'Sao Tome and Principe', 'ST');
	INSERT INTO public.country(id, name, code) VALUES (209, 'Saudi Arabia', 'SA');
	INSERT INTO public.country(id, name, code) VALUES (124, 'Senegal', 'SN');
	INSERT INTO public.country(id, name, code) VALUES (168, 'Serbia', 'RS');
	INSERT INTO public.country(id, name, code) VALUES (325, 'Seychelles', 'SC');
	INSERT INTO public.country(id, name, code) VALUES (7, 'Sierra Leone', 'SL');
	INSERT INTO public.country(id, name, code) VALUES (312, 'Singapore', 'SG');
	INSERT INTO public.country(id, name, code) VALUES (324, 'Sint Maarten', 'SX');
	INSERT INTO public.country(id, name, code) VALUES (321, 'Slovakia', 'SK');
	INSERT INTO public.country(id, name, code) VALUES (322, 'Slovenia', 'SI');
	INSERT INTO public.country(id, name, code) VALUES (284, 'Solomon Islands', 'SB');
	INSERT INTO public.country(id, name, code) VALUES (30, 'Somalia', 'SO');
	INSERT INTO public.country(id, name, code) VALUES (31, 'South Africa', 'ZA');
	INSERT INTO public.country(id, name, code) VALUES (281, 'South Georgia and the South Sandwich Islands', 'GS');
	INSERT INTO public.country(id, name, code) VALUES (4, 'South Sudan', 'SS');
	INSERT INTO public.country(id, name, code) VALUES (216, 'Spain', 'ES');
	INSERT INTO public.country(id, name, code) VALUES (49, 'Sri Lanka', 'LK');
	INSERT INTO public.country(id, name, code) VALUES (12, 'Sudan', 'SD');
	INSERT INTO public.country(id, name, code) VALUES (320, 'Suriname', 'SR');
	INSERT INTO public.country(id, name, code) VALUES (283, 'Svalbard and Jan Mayen', 'SJ');
	INSERT INTO public.country(id, name, code) VALUES (323, 'Sweden', 'SE');
	INSERT INTO public.country(id, name, code) VALUES (230, 'Switzerland', 'CH');
	INSERT INTO public.country(id, name, code) VALUES (11, 'Syrian Arab Republic', 'SY');
	INSERT INTO public.country(id, name, code) VALUES (315, 'Taiwan', 'TW');
	INSERT INTO public.country(id, name, code) VALUES (169, 'Tajikistan', 'TJ');
	INSERT INTO public.country(id, name, code) VALUES (137, 'Thailand', 'TH');
	INSERT INTO public.country(id, name, code) VALUES (179, 'The former Yugoslav Republic of Macedonia', 'MK');
	INSERT INTO public.country(id, name, code) VALUES (210, 'Timor-Leste', 'TL');
	INSERT INTO public.country(id, name, code) VALUES (150, 'Togo', 'TG');
	INSERT INTO public.country(id, name, code) VALUES (313, 'Tokelau', 'TK');
	INSERT INTO public.country(id, name, code) VALUES (314, 'Tonga', 'TO');
	INSERT INTO public.country(id, name, code) VALUES (329, 'Trinidad and Tobago', 'TT');
	INSERT INTO public.country(id, name, code) VALUES (128, 'Tunisia', 'TN');
	INSERT INTO public.country(id, name, code) VALUES (15, 'Turkey', 'TR');
	INSERT INTO public.country(id, name, code) VALUES (181, 'Turkmenistan', 'TM');
	INSERT INTO public.country(id, name, code) VALUES (326, 'Turks and Caicos Islands', 'TC');
	INSERT INTO public.country(id, name, code) VALUES (330, 'Tuvalu', 'TV');
	INSERT INTO public.country(id, name, code) VALUES (55, 'Uganda', 'UG');
	INSERT INTO public.country(id, name, code) VALUES (139, 'Ukraine', 'UA');
	INSERT INTO public.country(id, name, code) VALUES (224, 'United Arab Emirates', 'AE');
	INSERT INTO public.country(id, name, code) VALUES (255, 'United Kingdom of Great Britain & Northern Ireland', 'GB');
	INSERT INTO public.country(id, name, code) VALUES (88, 'United Republic of Tanzania', 'TZ');
	INSERT INTO public.country(id, name, code) VALUES (317, 'United States of America', 'US');
	INSERT INTO public.country(id, name, code) VALUES (333, 'United States Virgin Islands', 'VI');
	INSERT INTO public.country(id, name, code) VALUES (211, 'Uruguay', 'UY');
	INSERT INTO public.country(id, name, code) VALUES (174, 'Uzbekistan', 'UZ');
	INSERT INTO public.country(id, name, code) VALUES (319, 'Vanuatu', 'VU');
	INSERT INTO public.country(id, name, code) VALUES (212, 'Venezuela', 'VE');
	INSERT INTO public.country(id, name, code) VALUES (138, 'Viet Nam', 'VN');
	INSERT INTO public.country(id, name, code) VALUES (334, 'Wallis and Futuna', 'WF');
	INSERT INTO public.country(id, name, code) VALUES (215, 'Western Sahara', 'EH');
	INSERT INTO public.country(id, name, code) VALUES (22, 'Yemen', 'YE');
	INSERT INTO public.country(id, name, code) VALUES (47, 'Zambia', 'ZM');
	INSERT INTO public.country(id, name, code) VALUES (86, 'Zimbabwe', 'ZW');
